%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Dropbox\Postdoc\Articles WIP\INFORMS RAS 2018 Problem Solving
%    Competition\Data\RollingStockConnections.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/12 19:55:25

%% Initialize variables.
filename = [mainFolder 'RollingStockConnections.txt'];
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Day2 = dataArray{:, 1};
ArrivingTrain = dataArray{:, 2};
Location2 = dataArray{:, 3};
DepartingTrain = dataArray{:, 4};

%% restructure data
Nrows = length(Day2)
clear RSConnections
tic
jj=1;
for ii = 1:Nrows   % for 5-9-2017
    RSConnections(jj).Day = Day2(ii);
    RSConnections(jj).ArrivingTrain = (ArrivingTrain(ii));
    RSConnections(jj).Location = Location2{ii};
    RSConnections(jj).DepartingTrain = (DepartingTrain(ii));
    jj=jj+1;
end
toc 

save('RSConnections','RSConnections')
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans ArrivingTrain Location DepartingTrain Day